<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Logo Better Call Capybara</name>
   <tag></tag>
   <elementGuidId>9399d053-5a8a-46f2-acfd-c945cc3acc58</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//nav[@id='navbar']/div/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.navbar-brand.fs-3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>b488144c-64d0-4889-93e3-534728175921</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>navbar-brand fs-3</value>
      <webElementGuid>5994bf93-49c5-4c47-8475-1ee9b5c1f464</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Better Call Capybara</value>
      <webElementGuid>39911014-db3f-4d1f-937d-0b04777be0d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;navbar&quot;)/div[@class=&quot;container-fluid&quot;]/span[@class=&quot;navbar-brand fs-3&quot;]</value>
      <webElementGuid>b46e399f-1c50-4eb0-98de-f9d542149523</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//nav[@id='navbar']/div/span</value>
      <webElementGuid>9d9f5dfd-2f16-414d-beeb-8fbbbc51f949</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Queue'])[1]/preceding::span[1]</value>
      <webElementGuid>cd071862-5529-4193-9ce7-790c56011a08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cooking'])[1]/preceding::span[1]</value>
      <webElementGuid>45f8e0b2-cb45-4878-ac4f-34333b609b15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/span</value>
      <webElementGuid>83919ce1-00de-4c57-a179-8214b04b7790</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Better Call Capybara' or . = 'Better Call Capybara')]</value>
      <webElementGuid>f203f5be-e2d7-4d5e-b6ee-c393e97549ed</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
